version: "2"
services:
  graphql:
    build: ./graphql
    volumes:
      - ./graphql:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mongo
  web1:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    ports:
      - "8000:8000"
    links:
      - graphql
  mongo:
    image: mongo
    ports:
      - "27017:27017"
